apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-devops
spec:
  ingressClassName: nginx
  rules:
  - host: cicd.devops.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cicd-a
            port:
              number: 80
status:
  loadBalancer: {}